[pytest]
markers =
    regression: mark a test as regression scenario
    valid: mark a test as valid scenario
    invalid: mark a test as invalid scenario
    negative: mark a test as negative scenario
    positive: mark a test as positive scenario
    smoke: mark a test as smoke scenario
    parametrize: mark a test as parametrize scenario
    edge: mark a test as edge scenario
    special: mark a test as special scenario
    multiline: mark a test as multiline scenario
    empty: mark a test as empty scenario
    sanity: mark a test as sanity scenario
    exception: mark a test as exception scenario
    security: mark a test as security scenario
    parameterized: mark a test as parameterized scenario
    compatibility: mark a test as compatibility scenario
