# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=on_recent_a2f621b75b
ROOST_METHOD_SIG_HASH=on_recent_dd729fa775


```
Scenario 1: Test on_recent function with valid access_token
Details:
  TestName: test_on_recent_with_valid_access_token
  Description: This test is intended to verify the correct functionality of the on_recent function when provided with a valid access token.
Execution:
  Arrange: Initialize a session with a valid access_token. Stub the InstagramAPI client to return expected responses for user_recent_media.
  Act: Call the on_recent function.
  Assert: The function should return a string containing the navigation menu, user recent media and remaining API calls. There should be no exceptions thrown.
Validation:
  This test is important as it validates the core functionality of the on_recent function. The expected result aligns with the function's specifications and business requirements of fetching and displaying recent media for a user.

Scenario 2: Test on_recent function without access_token
Details:
  TestName: test_on_recent_without_access_token
  Description: This test is intended to verify the behavior of the on_recent function when there is no access token available in the session.
Execution:
  Arrange: Initialize a session without an access_token.
  Act: Call the on_recent function.
  Assert: The function should return a string 'Missing Access Token'. There should be no exceptions thrown.
Validation:
  This test is important as it verifies the function handles scenarios where there is no access token gracefully. The expected result aligns with the function's specifications and business requirements of requiring an access token to fetch recent media.

Scenario 3: Test on_recent function when InstagramAPI client throws an exception
Details:
  TestName: test_on_recent_with_API_exception
  Description: This test is intended to verify the behavior of the on_recent function when the InstagramAPI client throws an exception.
Execution:
  Arrange: Initialize a session with a valid access_token. Stub the InstagramAPI client to throw an exception when user_recent_media is called.
  Act: Call the on_recent function.
  Assert: The function should handle the exception gracefully and print the exception message. It should return a string containing the navigation menu and remaining API calls.
Validation:
  This test is important as it verifies the function is robust and can handle exceptions from the InstagramAPI client. The expected result aligns with the function's specifications and business requirements of handling API failures gracefully.
```

"""

# ********RoostGPT********
import pytest
from bottle import request
from instagram import client
from sample_app import on_recent
from unittest.mock import MagicMock, patch

class Test_SampleAppOnRecent:

    @pytest.mark.valid
    def test_on_recent_with_valid_access_token(self):
        # Arrange
        request.session = {'access_token': 'valid_access_token'}
        with patch('client.InstagramAPI') as mock_api:
            mock_media = MagicMock()
            mock_media.type = 'image'
            mock_media.get_low_resolution_url.return_value = 'http://test_url.com'
            mock_media.id = 'media_id'
            mock_media.like_count = 10
            mock_api_instance = MagicMock()
            mock_api_instance.user_recent_media.return_value = ([mock_media], None)
            mock_api.return_value = mock_api_instance

            # Act
            result = on_recent()

            # Assert
            assert 'valid_access_token' in result
            assert 'http://test_url.com' in result
            assert 'media_id' in result
            assert '10' in result
            assert mock_api_instance.x_ratelimit_remaining in result
            assert mock_api_instance.x_ratelimit in result

    @pytest.mark.invalid
    def test_on_recent_without_access_token(self):
        # Arrange
        request.session = {}

        # Act
        result = on_recent()

        # Assert
        assert result == 'Missing Access Token'

    @pytest.mark.negative
    def test_on_recent_with_API_exception(self):
        # Arrange
        request.session = {'access_token': 'valid_access_token'}
        with patch('client.InstagramAPI') as mock_api:
            mock_api_instance = MagicMock()
            mock_api_instance.user_recent_media.side_effect = Exception('API error')
            mock_api.return_value = mock_api_instance

            # Act
            result = on_recent()

            # Assert
            assert 'API error' in result
            assert mock_api_instance.x_ratelimit_remaining in result
            assert mock_api_instance.x_ratelimit in result
