# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=get_standard_resolution_url_c83a8cd397
ROOST_METHOD_SIG_HASH=get_standard_resolution_url_64deb3625d


Scenario 1: Test when object type is 'image'
Details:
  TestName: test_get_standard_resolution_url_image
  Description: This test verifies that the get_standard_resolution_url function returns the correct URL for an image.
Execution:
  Arrange: Create an object of the class, set the type attribute to 'image', and add a URL to the images['standard_resolution'] attribute.
  Act: Call the get_standard_resolution_url method on the object.
  Assert: Check if the returned URL is the same as the one set in the images['standard_resolution'] attribute.
Validation:
  This test is important because it ensures that the function correctly handles the case when the object type is 'image'. The expected result is that the URL returned is the same as the one set in the images['standard_resolution'] attribute.

Scenario 2: Test when object type is not 'image'
Details:
  TestName: test_get_standard_resolution_url_video
  Description: This test verifies that the get_standard_resolution_url function returns the correct URL for a video.
Execution:
  Arrange: Create an object of the class, set the type attribute to anything other than 'image', and add a URL to the videos['standard_resolution'] attribute.
  Act: Call the get_standard_resolution_url method on the object.
  Assert: Check if the returned URL is the same as the one set in the videos['standard_resolution'] attribute.
Validation:
  This test is important because it ensures that the function correctly handles the case when the object type is not 'image'. The expected result is that the URL returned is the same as the one set in the videos['standard_resolution'] attribute.

Scenario 3: Test when attribute 'images' or 'videos' is missing
Details:
  TestName: test_get_standard_resolution_url_missing_attr
  Description: This test verifies that the get_standard_resolution_url function handles the case when the 'images' or 'videos' attribute is missing.
Execution:
  Arrange: Create an object of the class and set the type attribute to 'image' or anything other than 'image'. Do not set the 'images' or 'videos' attribute.
  Act: Call the get_standard_resolution_url method on the object.
  Assert: Check if the function raises an appropriate exception (like AttributeError).
Validation:
  This test is important because it ensures that the function handles the case when the 'images' or 'videos' attribute is missing. The function should raise an appropriate exception in such cases, as it cannot return a URL.
"""

# ********RoostGPT********
import pytest
from models import Media

class Test_MediaGetStandardResolutionUrl:
    @pytest.mark.positive
    def test_get_standard_resolution_url_image(self):
        # Arrange
        obj = Media('user', 'position')
        obj.type = 'image'
        obj.images = {'standard_resolution': {'url': 'https://example.com/image.jpg'}}

        # Act
        result = obj.get_standard_resolution_url()

        # Assert
        assert result == 'https://example.com/image.jpg'

    @pytest.mark.positive
    def test_get_standard_resolution_url_video(self):
        # Arrange
        obj = Media('user', 'position')
        obj.type = 'video'
        obj.videos = {'standard_resolution': {'url': 'https://example.com/video.mp4'}}

        # Act
        result = obj.get_standard_resolution_url()

        # Assert
        assert result == 'https://example.com/video.mp4'

    @pytest.mark.negative
    def test_get_standard_resolution_url_missing_attr(self):
        # Arrange
        obj = Media('user', 'position')
        obj.type = 'image'

        # Act and Assert
        with pytest.raises(AttributeError):
            obj.get_standard_resolution_url()
