# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type  and AI Model 

ROOST_METHOD_HASH=__init___8ce661cacf
ROOST_METHOD_SIG_HASH=__init___9850394e1f


```
Scenario 1: Test default initialisation of the given class
Details:
  TestName: test_default_initialisation
  Description: This test is needed to verify that the class's constructor will correctly assign the default values to fields when no kwargs are provided.
Execution:
  Arrange: No setup is necessary for this test.
  Act: Invoke the "__init__" function with only the "api" argument.
  Assert: Check that "as_generator" is False, "pagination_format" is 'next_url', "return_json" is False, "max_pages" is 3, "with_next_url" is None and "parameters" is an empty dictionary
Validation:
  This test ensures that the default initialization of the class follows the expected behavior. If successful, it means that users of this class can instantiate objects without providing all parameters and rely on intelligent defaults.

Scenario 2: Test initialization with as_generator set to True
Details:
  TestName: test_initialisation_as_generator_true
  Description: This test verifies that the "__init__" function correctly assigns the 'next_url' value to the "pagination_format" field when "as_generator" is set to True.
Execution:
  Arrange: No setup is necessary for this test.
  Act: Invoke the "__init__" function with "api" argument and "as_generator" set to True.
  Assert: Check that "as_generator" is True and "pagination_format" is 'next_url'.
Validation:
  This test ensures that the "as_generator" flag influences the "pagination_format" as per the business logic encapsulated in the "__init__" function. If successful, it will prove that the "as_generator" property correctly sets the "pagination_format" field.

Scenario 3: Test initialization with different "max_pages" value
Details:
  TestName: test_initialisation_max_pages
  Description: This test is checking that the "__init__" function correctly sets the "max_pages" field to the provided value, rather than using the default.
Execution:
  Arrange: No setup is necessary for this test.
  Act: Invoke the "__init__" function with "api" argument and "max_pages" set to a value other than 3.
  Assert: Check that "max_pages" value matches the provided value.
Validation:
  The "max_pages" property allows controlling the pagination behavior of the class. This test ensures that the assigned "max_pages" in the "__init__" function correctly sets this property, allowing users to influence the class's behavior.

Scenario 4: Test initialization with non-default "pagination_format", when "as_generator" is False
Details:
  TestName: test_initialisation_pagination_format
  Description: This test verifies that custom "pagination_format" can be set when "as_generator" is not True.
Execution:
  Arrange: No setup is necessary for this test.
  Act: Invoke the "__init__" function with "api", "as_generator" set to False and "pagination_format" set to a value other than 'next_url'.
  Assert: Check that "pagination_format" is set to the provided value.
Validation:
  This test ensures that the "pagination_format" can be customized when "as_generator" is not True, aligning with the encapsulated business logic in the "__init__" function.

Scenario 5: Test initialisation with additional parameters in "args" and "kwargs".
Details:
  TestName: test_initialisation_with_additional_args_kwargs
  Description: This test is to verify that additional parameters are correctly processed and incorporated into "parameters".
Execution:
  Arrange: No setup is necessary for this test.
  Act: Invoke the "__init__" function with 'api', additional args and kwargs included.
  Assert: Check that "parameters" include the provided args and kwargs.
Validation:
  This test validates the correct assignment of extra properties by confirming that provided "args" and "kwargs" are correctly incorporated into the "parameters" dictionary.
```

"""

# ********RoostGPT********
import urllib
from oauth2 import OAuth2Request
import re
from json_import import simplejson
import hmac
from hashlib import sha256
import six
from six.moves.urllib.parse import quote
import sys
import pytest

from instagram.bind import InstagramAPIMethod

class Test_InstagramApiMethodInit:
    
    def test_default_initialisation(self):
        instance = InstagramAPIMethod.__init__(self, "api")
        assert instance.as_generator == False
        assert instance.pagination_format == 'next_url'
        assert instance.return_json == False
        assert instance.max_pages == 3
        assert instance.with_next_url == None
        assert instance.parameters == {}
    
    def test_initialisation_as_generator_true(self):
        instance = InstagramAPIMethod.__init__(self, "api", as_generator=True)
        assert instance.as_generator == True
        assert instance.pagination_format == 'next_url'
    
    def test_initialisation_max_pages(self):
        instance = InstagramAPIMethod.__init__(self, "api", max_pages=5)
        assert instance.max_pages == 5

    def test_initialisation_pagination_format(self):
        instance = InstagramAPIMethod.__init__(self, "api", as_generator=False, pagination_format='different_format')
        assert instance.pagination_format == 'different_format'
        
    def test_initialisation_with_additional_args_kwargs(self):
        additional_args = ['arg1', 'arg2']
        additional_kwargs = {'kw1': 'value1', 'kw2': 'value2'}
        instance = InstagramAPIMethod.__init__(self, "api", *additional_args, **additional_kwargs)
        assert instance.parameters['kw1'] == 'value1'
        assert instance.parameters['kw2'] == 'value2'
