# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_data_for_exchange_15d227ca17
ROOST_METHOD_SIG_HASH=_data_for_exchange_698df60ddf


Scenario 1: Validate Authorization Code Flow
Details:
  TestName: test_with_authorization_code_only
  Description: This test checks if the function works correctly when only the code parameter is provided. 
Execution:
  Arrange: Initialize function with valid client_id, client_secret and redirect_uri. Create a value for code.
  Act: Invoke the function with only the code parameter.
  Assert: Check if the returned encoded string contains the correct 'authorization_code' and the code value.
Validation:
  This test validates the basic operation of the function with authorization code. This is the base case and indicates normal functionality.

Scenario 2: Validate Resource Owner Password Credential Flow
Details:
  TestName: test_with_username_and_password
  Description: This test validates user authentication directly with username and password. 
Execution:
  Arrange: Initialize function with valid client_id, client_secret. Create a username, password.
  Act: Invoke the function with username and password.
  Assert: Verify that the returned encoded string contains the correct 'password' grant_type, and the provided username and password.
Validation:
  This test checks if the function is correctly implementing the 'Resource Owner Password Credential' grant, important for applications that have a high degree of trust with the user.

Scenario 3: Validate inclusion of optional scope in Resource Owner Password Credential Flow
Details:
  TestName: test_with_username_password_and_scope
  Description: Test the case where the scope parameter is included with username and password.
Execution:
  Arrange: Initialize function with client_id, client_secret. Create a username, password, and scope array.
  Act: Invoke the function with username, password, and scope.
  Assert: Verify that 'scope' exists in the returned encoded string, alongside the provided grant_type, username, and password.
Validation:
  The test checks if the function correctly handles a provided scope, which can be used to limit the areas of functionality a client has access to.

Scenario 4: Test function with user_id only
Details:
  TestName: test_with_user_id_only
  Description: Test to check proper parameter setting for user_id only for identification.
Execution:
  Arrange: Initialize function with valid client_id, client_secret, and user_id.
  Act: Call function with user_id parameter.
  Assert: Verification, if user_id is specified and set correctly in the returned encoded string, can be done.
Validation:
  User_id might be solely used in specific scenarios for identification, which is why validating this behavior is important.

Scenario 5: Validate function handling when no parameters are provided
Details:
  TestName: test_with_no_parameters
  Description: This test is to verify how the function behaves when no optional parameters are provided. 
Execution:
  Arrange: Initialize function with valid client_id, client_secret, and redirect_uri. 
  Act: Invoke the function without any optional parameters.
  Assert: Verify that the returned encoded string only contains the initial client_params and the grant type set to 'authorization_code'.
Validation:
  The test asserts that the function correctly handles situations when no optional parameters are provided. It also ensures that the correct default 'grant_type' is set as 'authorization_code'.
"""

# ********RoostGPT********
import pytest
from urllib.parse import urlencode
from oauth2 import OAuth2AuthExchangeRequest

class Test_OAuth2AuthExchangeRequestDataForExchange:

    @pytest.mark.smoke
    def test_with_authorization_code_only(self):
        # Arrange
        request = OAuth2AuthExchangeRequest('test_client_id', 'test_client_secret', 'test_uri')
        code = 'test_code'

        # Act
        result = request._data_for_exchange(code=code)

        # Assert
        expected_result = urlencode({'client_id': 'test_client_id', 'client_secret': 'test_client_secret', 'redirect_uri': 'test_uri', 'grant_type': 'authorization_code', 'code': code})
        assert result == expected_result

    @pytest.mark.smoke
    def test_with_username_and_password(self):
        # Arrange
        request = OAuth2AuthExchangeRequest('test_client_id', 'test_client_secret','test_uri')
        username = 'test_username'
        password = 'test_password'

        # Act
        result = request._data_for_exchange(username=username, password=password)

        # Assert
        expected_result = urlencode({'client_id': 'test_client_id', 'client_secret': 'test_client_secret', 'redirect_uri': 'test_uri','grant_type': 'password', 'username': username, 'password': password})
        assert result == expected_result

    @pytest.mark.smoke
    def test_with_username_password_and_scope(self):
        # Arrange
        request = OAuth2AuthExchangeRequest('test_client_id', 'test_client_secret','test_uri')
        username = 'test_username'
        password = 'test_password'
        scope = ['read', 'write']

        # Act
        result = request._data_for_exchange(username=username, password=password, scope=scope)

        # Assert
        expected_result = urlencode({'client_id': 'test_client_id', 'client_secret': 'test_client_secret', 'redirect_uri': 'test_uri','grant_type': 'password', 'username': username, 'password': password, 'scope': ' '.join(scope)})
        assert result == expected_result

    @pytest.mark.smoke
    def test_with_user_id_only(self):
        # Arrange
        request = OAuth2AuthExchangeRequest('test_client_id', 'test_client_secret','test_uri')
        user_id = 'test_user_id'

        # Act
        result = request._data_for_exchange(user_id=user_id)

        # Assert
        expected_result = urlencode({'client_id': 'test_client_id', 'client_secret': 'test_client_secret', 'redirect_uri': 'test_uri','grant_type': 'authorization_code', 'user_id': user_id})
        assert result == expected_result

    @pytest.mark.smoke
    def test_with_no_parameters(self):
        # Arrange
        request = OAuth2AuthExchangeRequest('test_client_id', 'test_client_secret','test_uri')

        # Act
        result = request._data_for_exchange()

        # Assert
        expected_result = urlencode({'client_id': 'test_client_id', 'client_secret': 'test_client_secret', 'redirect_uri': 'test_uri','grant_type': 'authorization_code'})
        assert result == expected_result
