# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___26c10bceca
ROOST_METHOD_SIG_HASH=__init___ac40efa6f3


```
Scenario 1: Test Behaviour When status_code is not provided
Details:
  TestName: test_init_no_status_code
  Description: This test verifies the constructor default behaviour when status code is not provided.
Execution:
  Arrange: Instantiate an object of the class without providing a status_code.
  Act: No specific actions are needed besides the initialization.
  Assert: The status_code attribute of the object should be None.
Validation:
  It's essential to verify the default behavior of the constructor since the status_code is not a required argument.

Scenario 2: Test Behaviour When status_code is provided
Details:
  TestName: test_init_with_status_code
  Description: This test verifies the correct assignment of status_code when the constructor is called with this argument.
Execution:
  Arrange: Create an instance of the class providing a specific status_code.
  Act: No actions required besides initialization.
  Assert: The status_code attribute of the object should be equal to the status code provided at initialization.
Validation:
  Testing the correct assignment of the status_code attribute in constructor assures that status codes will be correctly stored by instances for later use.

Scenario 3: Test Behaviour When error_message is provided
Details:
  TestName: test_init_with_error_message
  Description: This test verifies the correct assignment of error_message attribute when the constructor is called with this argument.
Execution:
  Arrange: Instantiate the class providing a specific error_message.
  Act: No actions required further to initialization.
  Assert: The error_message attribute of the object should match the error message provided at initialization.
Validation:
  Error messages are vital for debugging and user communication. Ensuring their correct assignment at the constructor assures this functionality will perform satisfactorily.

Scenario 4: Test initialization with arbitrary status_code types
Details:
  TestName: test_init_arbitrary_status_code_type
  Description: This test validates the ability of the constructor to handle status_code of different types and still function correctly.
Execution:
  Arrange: Initialize the class passing status_codes of different types (integer, string, float).
  Act: No actions required besides initialization.
  Assert: The status_code attribute should always match the respective input, regardless of its type.
Validation:
  Although typically status codes are integers, the class might be used with custom status codes of different types. Verifying this flexibility ensures class functionality in wider usage scenarios.
```
"""

# ********RoostGPT********
import pytest
from InstagramError import InstagramClientError 

class Test_InstagramClientErrorInit:
    # Scenario 1: Test Behaviour When status_code is not provided
    def test_init_no_status_code(self): 
        error = InstagramClientError(error_message="No status code")
        assert error.status_code is None

    # Scenario 2: Test Behaviour When status_code is provided
    def test_init_with_status_code(self): 
        error = InstagramClientError(error_message="Status code 200 provided", status_code=200)
        assert error.status_code == 200

    # Scenario 3: Test Behaviour When error_message is provided
    def test_init_with_error_message(self): 
        error_message = "Custom error message"
        error = InstagramClientError(error_message=error_message)
        assert error.error_message == error_message

    # Scenario 4: Test initialization with arbitrary status_code types
    def test_init_arbitrary_status_code_type(self): 
        status_code_integer = 200
        status_code_string = "300"
        status_code_float = 400.0
        error_with_int = InstagramClientError(error_message="Int type", status_code=status_code_integer)
        error_with_str = InstagramClientError(error_message="Str type", status_code=status_code_string)
        error_with_float = InstagramClientError(error_message="Float type", status_code=status_code_float)
        assert error_with_int.status_code == status_code_integer
        assert error_with_str.status_code == status_code_string
        assert error_with_float.status_code == status_code_float
