# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type  and AI Model 

ROOST_METHOD_HASH=__str___0d5d6f8d02
ROOST_METHOD_SIG_HASH=__str___57494adc14


Scenario 1: Testing if the function returns the correct format when status code is provided
Details:
  TestName: test_correct_format_with_status_code
  Description: This test is intended to verify that the function returns a string formatted as "(status_code) error_message" if a status_code is provided.
Execution:
  Arrange: Initialize an object of the class with a string error message and a non-null status code.
  Act: Invoke the __str__ function on the initialized object.
  Assert: Check if the return value of the function is a string formatted as "(status_code) error_message".
Validation:
  This test verifies that status_code and error_message are concatenated correctly, if the status code is provided. This is a core feature of the __str__ function.

Scenario 2: Testing if the function returns the correct format when status code is not provided
Details:
  TestName: test_correct_format_without_status_code
  Description: This test is intended to verify that the function returns a string as just "error_message" if no status_code is provided.
Execution:
  Arrange: Initialize an object of the class with a string error message and no status code.
  Act: Invoke the __str__ function on the initialized object.
  Assert: Check if the return value of the function is string "error_message".
Validation:
  This test confirms that the function can handle missing status code. It ensures that the error_message is returned without the status code if the latter is not provided.

Scenario 3: Testing if the function handles empty error_message correctly
Details:
  TestName: test_empty_error_message
  Description: This test is intended to verify that the function returns correct string if an empty error_message is provided.
Execution:
  Arrange: Initialize an object of the class with an empty string as error_message and a status code.
  Act: Invoke the __str__ function on the initialized object.
  Assert: Check if the return value of the function is a string formatted as "(status_code) ".
Validation:
  This test aims to confirm that the function can handle empty error messages. As per the business logic, even if the error message is empty, the function should return it as per the format.

Scenario 4: Testing if the function handles None error_message correctly
Details:
  TestName: test_None_error_message
  Description: This test is intended to verify that the function returns correct string if null error_message is provided.
Execution:
  Arrange: Initialize an object of the class with a None error_message and a status code.
  Act: Invoke the __str__ function on the initialized object.
  Assert: Check if the return value of the function is a string formatted as "(status_code) None".
Validation:
  This test checks that the function handles None values in error messages correctly. It ensures that if a None error message is provided, the None value is represented correctly in the output string.

"""

# ********RoostGPT********
import pytest
from instagram.bind import InstagramClientError

class Test_InstagramClientErrorStr:

    @pytest.mark.regression
    def test_correct_format_with_status_code(self):
        error = InstagramClientError("Test error", status_code=404)
        assert error.__str__() == "(404) Test error"

    @pytest.mark.regression
    def test_correct_format_without_status_code(self):
        error_without_status_code = InstagramClientError("Test error")
        assert error_without_status_code.__str__() == "Test error"
        
    @pytest.mark.regression
    def test_empty_error_message(self):
        empty_error_message = InstagramClientError("", status_code=404)
        assert empty_error_message.__str__() == "(404) "

    @pytest.mark.regression
    def test_None_error_message(self):
        None_error_message = InstagramClientError(None, status_code=404)
        assert None_error_message.__str__() == "(404) None"
