# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_build_pagination_info_7cb90732ec
ROOST_METHOD_SIG_HASH=_build_pagination_info_fb4505ce87


Scenario 1: Validating when pagination_format equals 'next_url'
Details:
  Test Name: test_pagination_format_next_url
  Description: This test is intended to verify if the function correctly return `next_url` from pagination dictionary when `pagination_format == 'next_url'`.
Execution:
  Arrange: Initialize an object and the `pagination_format` as 'next_url', and content_obj dictionary with 'pagination' as a nested dictionary including 'next_url'.
  Act: Invoke '_build_pagination_info' function passing given content_obj as parameter. 
  Assert: The return value should be the 'next_url' value in the pagination sub-dictionary.
Validation:
  This is fundamental to ensure that the function properly handles and returns 'next_url' when this pagination format is requested.

Scenario 2: Validating when pagination_format equals 'dict'
Details:
  Test Name: test_pagination_format_dict
  Description: This test is intended to verify if the function correctly return the entire `pagination` dictionary when `pagination_format == 'dict'`.
Execution:
  Arrange: Initialize an object and the `pagination_format` as 'dict'. Also, Prepare content_obj dictionary with 'pagination' as a nested dictionary. 
  Act: Invoke '_build_pagination_info' function passing given content_obj as parameter. 
  Assert: The return value should be the entire 'pagination' sub-dictionary in content_obj.
Validation:
  The test checks the function's ability to return the entire pagination dictionary as per requirement, helping to validate the variety in return format options.

Scenario 3: Validating Exception is raised for invalid pagination_format
Details:
  Test Name: test_invalid_pagination_format
  Description: This test is intended to verify if an Exception is correctly raised when the `pagination_format` does not equal 'next_url' or 'dict'.
Execution:
  Arrange: Initialize an object with the `pagination_format` as something other than 'next_url' or 'dict', and prepare a content_obj dictionary with 'pagination' as a nested dictionary. 
  Act: Invoke '_build_pagination_info' function passing given content_obj as parameter. 
  Assert: An Exception with the string 'Invalid value for pagination_format' should be raised.
Validation:
  This scenario is significant in ensuring the function handles invalid formatting by not attempting to process it and instead returning an Exception.

Scenario 4: Validating the behavior when pagination is missing in content_obj
Details:
  Test Name: test_pagination_missing_in_content_obj
  Description: The test checks the behavior of the function when the 'pagination' key is missing in content_obj.
Execution:
  Arrange: Create an object instance and initialize content_obj as an empty dictionary.
  Act: Invoke `_build_pagination_info` with content_obj as a parameter.
  Assert: As no 'pagination' key is present in the content_obj, it should return None irrespective of what pagination_format is.
Validation:
  This test confirms the function's defensive coding practices, handling cases where the 'pagination' key is missing in the input.
"""

# ********RoostGPT********
import pytest
from bind import _build_pagination_info

class Test_BindBuildPaginationInfo:

    @pytest.mark.valid
    def test_pagination_format_next_url(self):
        # Arrange
        obj = Bind(pagination_format='next_url') 
        content_obj = {'pagination': { 'next_url': 'https://example.com'}} 

        # Act
        result = obj._build_pagination_info(content_obj) 

        # Assert
        assert result == 'https://example.com'

    @pytest.mark.valid
    def test_pagination_format_dict(self):
        # Arrange
        obj = Bind(pagination_format='dict') 
        pagination_dict = { 'next_url': 'https://example.com', 'prev_url': 'https://prev.example.com'}
        content_obj = {'pagination': pagination_dict} 

        # Act
        result = obj._build_pagination_info(content_obj) 

        # Assert
        assert result == pagination_dict

    @pytest.mark.exception
    def test_invalid_pagination_format(self):
        # Arrange
        obj = Bind(pagination_format='invalid_format') 
        content_obj = {'pagination': { 'next_url': 'https://example.com'}} 

        # Act & Assert
        with pytest.raises(Exception) as exinfo:
            obj._build_pagination_info(content_obj) 
        assert str(exinfo.value) == 'Invalid value for pagination_format: invalid_format'
        
    @pytest.mark.exception
    def test_pagination_missing_in_content_obj(self):
        # Arrange
        obj = Bind(pagination_format='dict') 
        content_obj = {} 

        # Act
        result = obj._build_pagination_info(content_obj)

        # Assert
        assert result is None
