# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type  and AI Model 

ROOST_METHOD_HASH=_build_pagination_info_7cb90732ec
ROOST_METHOD_SIG_HASH=_build_pagination_info_fb4505ce87


Scenario 1: Validate the Pagination Info with next_url format
Details:
  TestName: test_build_pagination_info_with_next_url_format
  Description: This test checks if the method handles pagination with the 'next_url' format correctly. It is expected to return the next_url from the given content_obj dictionary.
Execution:
  Arrange: Create an instance of the class with 'next_url' as the pagination_format. Also prepare a content_obj dictionary containing a 'pagination' key with a nested 'next_url' key.
  Act: Call the _build_pagination_info method with the prepared content_obj dictionary as the argument.
  Assert: Check if the returned value matches the 'next_url' from the content_obj dictionary.
Validation:
  This test validates the business requirement that supports pagination URLs for API requests. It confirms whether the function correctly extracts the next_url when the pagination format is 'next_url'.

Scenario 2: Validate the Pagination Info with dict format
Details:
  TestName: test_build_pagination_info_with_dict_format
  Description: This test verifies if the method handles pagination with the 'dict' format correctly. It is expected to return the entire pagination dictionary from the given content_obj dictionary.
Execution:
  Arrange: Create an instance of the class with 'dict' as the pagination_format. Also prepare a content_obj dictionary containing a 'pagination' key with some dummy data.
  Act: Call the _build_pagination_info method with the prepared content_obj dictionary as the argument.
  Assert: Check if the returned value matches the 'pagination' dictionary from the content_obj dictionary.
Validation:
  This test validates the business requirement of having a dictionary format for pagination information. It confirms whether the function correctly returns the whole dictionary when the pagination format is 'dict'.

Scenario 3: Validate the Pagination Info with an Invalid format
Details:
  TestName: test_build_pagination_info_with_invalid_format
  Description: This test checks if the method raises an Exception when given an invalid pagination format.
Execution:
  Arrange: Create an instance of the class with some invalid value as the pagination_format. Also prepare a content_obj dictionary with some dummy data.
  Act: Call the _build_pagination_info method with the prepared content_obj dictionary as the argument and expect it to raise an exception.
  Assert: Make sure an exception is raised and the error message matches the expected message.
Validation:
  This scenario verifies the function's error handling for invalid input. The function should be able to recognise and reject invalid pagination formats, ensuring the resilience and correct operation of the application.

"""

# ********RoostGPT********
import pytest
from instagram.bind import InstagramAPIMethod

class Test_InstagramApiMethodBuildPaginationInfo:
    @pytest.mark.regression
    @pytest.mark.positive
    def test_build_pagination_info_with_next_url_format(self):
        # Arrange
        instagram_api = InstagramAPIMethod(api=None, as_generator=True)
        content_obj = {'pagination': {'next_url': 'https://api.instagram.com/v1/photos'}}

        # Act
        result = instagram_api._build_pagination_info(content_obj)
        
        # Assert
        assert result == 'https://api.instagram.com/v1/photos'

    @pytest.mark.regression
    @pytest.mark.positive
    def test_build_pagination_info_with_dict_format(self):
        # Arrange
        instagram_api = InstagramAPIMethod(api=None, pagination_format='dict')
        content_obj = {'pagination': {'page': 2, 'perPage': 20, 'total': 100}}

        # Act
        result = instagram_api._build_pagination_info(content_obj)
        
        # Assert
        assert result == {'page': 2, 'perPage': 20, 'total': 100}

    @pytest.mark.regression
    @pytest.mark.negative
    def test_build_pagination_info_with_invalid_format(self):
        # Arrange
        instagram_api = InstagramAPIMethod(api=None, pagination_format='invalid')
        content_obj = {'pagination': {'page': 2}}

        # Act
        with pytest.raises(Exception) as exc:
            instagram_api._build_pagination_info(content_obj)
        
        # Assert
        assert str(exc.value) == 'Invalid value for pagination_format: invalid'
