# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type  and AI Model 

ROOST_METHOD_HASH=_data_for_exchange_15d227ca17
ROOST_METHOD_SIG_HASH=_data_for_exchange_698df60ddf


Scenario 1: Testing method with provided code
Details:
  TestName: test_data_for_exchange_with_code
  Description: This test ensures that the method performs well when the 'code' is provided. 
Execution:
  Arrange: Initiate a new instance of the class, with all the necessary attributes for the api object. Provide a code for the test.
  Act: Call the '_data_for_exchange' function using the instance with code as parameter.
  Assert: Check whether the returned value of the function includes provided 'code' and both 'code' and 'grant_type' being 'authorization_code'.
Validation:
  This test assures that when the code is provided, the function updates client_params with it and keeps grant_type as 'authorization_code'.

Scenario 2: Testing method with provided username and password but no scope
Details:
  TestName: test_data_for_exchange_with_username_password_no_scope
  Description: This test ensures proper execution of method when 'username' and 'password' are given, but no 'scope'.
Execution:
  Arrange: Initiate a new instance of the class with the necessary attributes for the api object. Provide a username and password for the test.
  Act: Invoke '_data_for_exchange' function using instance with username and password as parameters.
  Assert: Check whether the function's returned value includes provided 'username' and 'password' and that 'grant_type' is 'password'.
Validation:
  This test guarantees that, when username and password parameters are provided, the function correctly updates client_params with them and that 'grant_type' is 'password'.

Scenario 3: Testing method with provided username, password and scope
Details:
  TestName: test_data_for_exchange_with_username_password_scope
  Description: This test validates the execution of method when 'username', 'password', and 'scope' parameters are provided.
Execution:
  Arrange: Initiate a new instance of the class. Populate necessary attributes for the api object. Provide username, password, and scope for the test.
  Act: Call the '_data_for_exchange' function using the instance with username, password and scope as parameters.
  Assert: Verify if the returned value of the function contains 'username', 'password', and space-joined 'scope' as expected.
Validation:
  This test ensures that, when the function is called with username, password, and scope parameters, the function correctly adds them to client_params.

Scenario 4: Testing method with provided user_id
Details:
  TestName: test_data_for_exchange_with_user_id
  Description: This test gauges the performance of the method when only 'user_id' is given.
Execution:
  Arrange: Initiate a new instance of the class. Populate necessary attributes for the api object. Provide a user_id for the test.
  Act: Invoke '_data_for_exchange' function with the instance, supplying user_id as parameter.
  Assert: Check whether function's returned value includes provided 'user_id'.
Validation:
  The test ensures that the function correctly updates client_params with 'user_id' when called with it as the only parameter. 

Scenario 5: Testing method with no parameters 
Details:
  TestName: test_data_for_exchange_no_parameters
  Description: This test checks the behavior of the method when called with no parameters.
Execution:
  Arrange: Initiate a new instance of the class. Populate necessary attributes for the api object.
  Act: Call the '_data_for_exchange' function using the instance with no parameters.
  Assert: Check if 'client_id', 'client_secret', 'redirect_uri', 'grant_type' are included in the returned value, with 'grant_type' being 'authorization_code'.
Validation:
  This test validates that the function correctly constructs client_params with default values when called without parameters.

"""

# ********RoostGPT********
import pytest
from instagram.oauth2 import OAuth2AuthExchangeRequest
from urllib.parse import parse_qs

class Test_OAuth2AuthExchangeRequestDataForExchange:

    @pytest.mark.parametrize("code", ['test_code'])
    def test_data_for_exchange_with_code(self, code):
        req = OAuth2AuthExchangeRequest(api={'client_id': 'test', 'client_secret': 'test', 'redirect_uri': 'test'})
        response = req._data_for_exchange(code)
        assert parse_qs(response) == {'client_id': ['test'], 'client_secret': ['test'], 'redirect_uri': ['test'], 'grant_type': ['authorization_code'], 'code': [code]}

    @pytest.mark.parametrize("username, password", [('test_username', 'test_password')])
    def test_data_for_exchange_with_username_password_no_scope(self, username, password):
        req = OAuth2AuthExchangeRequest(api={'client_id': 'test', 'client_secret': 'test', 'redirect_uri': 'test'})
        response = req._data_for_exchange(username=username, password=password)
        assert parse_qs(response) == {'client_id': ['test'], 'client_secret': ['test'], 'redirect_uri': ['test'], 'grant_type': ['password'], 'username': [username], 'password': [password]}

    @pytest.mark.parametrize("username, password, scope", [('test_username', 'test_password', ['scope1', 'scope2'])])
    def test_data_for_exchange_with_username_password_scope(self, username, password, scope):
        req = OAuth2AuthExchangeRequest(api={'client_id': 'test', 'client_secret': 'test', 'redirect_uri': 'test'})
        response = req._data_for_exchange(username=username, password=password, scope=scope)
        assert parse_qs(response) == {'client_id': ['test'], 'client_secret': ['test'], 'redirect_uri': ['test'], 'grant_type': ['password'], 'username': [username], 'password': [password], 'scope': [' '.join(scope)]}

    @pytest.mark.parametrize("user_id", ['test_user_id'])
    def test_data_for_exchange_with_user_id(self, user_id):
        req = OAuth2AuthExchangeRequest(api={'client_id': 'test', 'client_secret': 'test', 'redirect_uri': 'test'})
        response = req._data_for_exchange(user_id=user_id)
        assert parse_qs(response) == {'client_id': ['test'], 'client_secret': ['test'], 'redirect_uri': ['test'], 'grant_type': ['authorization_code'], 'user_id': [user_id]}

    def test_data_for_exchange_no_parameters(self):
        req = OAuth2AuthExchangeRequest(api={'client_id': 'test', 'client_secret': 'test', 'redirect_uri': 'test'})
        response = req._data_for_exchange()
        assert parse_qs(response) == {'client_id': ['test'], 'client_secret': ['test'], 'redirect_uri': ['test'], 'grant_type': ['authorization_code']}
