# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=deregister_callback_d397189279
ROOST_METHOD_SIG_HASH=deregister_callback_9225e150e0


Scenario 1: Callback is successfully removed
Details:
  TestName: test_callback_removed_successfully
  Description: This test verifies that the deregister_callback function successfully removes a callback linked to an object_type when that callback exists.
Execution:
  Arrange: Initialize an instance of the class. Assign a callback to an object_type in the instance's callbacks dictionary.
  Act: Call the deregister_callback function, supplying the relevant object_type and callback.
  Assert: Check that the callback was removed from the object_type's callbacks.
Validation:
  This test confirms that the function successfully deletes a callback when it exists. It's crucial for ensuring the function's effectiveness in callback management.

Scenario 2: Nonexistent callback can't be removed
Details:
  TestName: test_nonexistent_callback_removal_fails
  Description: This test validates that an error is raised when attempting to remove a nonexisting callback from an object_type.
Execution:
  Arrange: Initialize an instance of the class. Assign no callback to any object_type in the instance's callbacks dictionary.
  Act: Call the deregister_callback function, supplying an object_type and a callback that has not been registered.
  Assert: Expect a ValueError due to the removal of a non-existing callback.
Validation:
  This test verifies the function's error management under exceptional circumstances. It exposes issues that might arise when the function is used in different contexts.

Scenario 3: Callback removal doesn't affect other callbacks
Details:
  TestName: test_callback_removal_does_not_affect_others
  Description: This test ensures that removing a callback from an object_type does not affect other callbacks related to that object_type.
Execution:
  Arrange: Initialize an instance of the class. Assign multiple callbacks to the same object_type in the instance's callbacks dictionary.
  Act: Call the deregister_callback function, supplying the object_type and a callback to be removed.
  Assert: Confirm that only the specified callback got removed and the other callbacks linked to the same object_type remained unaffected.
Validation:
  This test checks that the function only modifies its target callback and does not affect any unrelated callbacks. It's essential for ensuring the function's accuracy and efficiency in managing multiple callbacks. 

Scenario 4: Removing callback from a non-existing object_type
Details:
  TestName: test_removing_callback_from_nonexisting_object_type
  Description: This test examines the behavior of the function when a callback is removed from a non-existing object_type.
Execution:
  Arrange: Initialize an instance of the class. Do not assign any callback to any object_type in the instance's callbacks dictionary.
  Act: Call the deregister_callback function, supplying a non-existing object_type and a callback.
  Assert: Expect a ValueError since there's no callbacks list for the provided object_type from which to remove a callback.
Validation:
  This test helps in assuring exception management when working with non-existing object_types. It helps in ensuring stability when the function encounters unexpected inputs.

"""

# ********RoostGPT********
import hmac
import hashlib
import pytest
from json_import import simplejson
from subscriptions import SubscriptionsReactor

class Test_SubscriptionsReactorDeregisterCallback:

    def test_callback_removed_successfully(self):
        # Arrange
        reactor = SubscriptionsReactor()
        object_type = "type1"
        callback = "callback1"
        reactor.callbacks[object_type] = [callback]

        # Act
        reactor.deregister_callback(object_type, callback)

        # Assert
        assert callback not in reactor.callbacks[object_type]

    def test_nonexistent_callback_removal_fails(self):
        # Arrange
        reactor = SubscriptionsReactor()
        object_type = "type1"
        callback = "callback1"

        # Assert
        with pytest.raises(ValueError):
            # Act
            reactor.deregister_callback(object_type, callback)

    def test_callback_removal_does_not_affect_others(self):
        # Arrange
        reactor = SubscriptionsReactor()
        object_type = "type1"
        callback1 = "callback1"
        callback2 = "callback2"
        reactor.callbacks[object_type] = [callback1, callback2]

        # Act
        reactor.deregister_callback(object_type, callback1)

        # Assert
        assert callback1 not in reactor.callbacks[object_type]
        assert callback2 in reactor.callbacks[object_type]

    def test_removing_callback_from_nonexisting_object_type(self):
        # Arrange
        reactor = SubscriptionsReactor()
        object_type = "type1"
        callback = "callback1"

        # Assert
        with pytest.raises(ValueError):
            # Act
            reactor.deregister_callback(object_type, callback)
