# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_build_pagination_info_7cb90732ec
ROOST_METHOD_SIG_HASH=_build_pagination_info_fb4505ce87


Scenario 1: Test when pagination_format is 'next_url' and 'next_url' is in the content_obj
Details:
  TestName: test_build_pagination_info_next_url
  Description: This test is intended to verify that the function returns the 'next_url' value from the pagination dictionary when pagination_format is set as 'next_url'.
Execution:
  Arrange: Initialize an instance of the class with pagination_format set to 'next_url'. Prepare a content_obj with a 'pagination' dictionary containing a 'next_url' key-value pair.
  Act: Call the _build_pagination_info method with the prepared content_obj.
  Assert: Check that the returned value matches the 'next_url' value from the content_obj.
Validation:
  This test verifies that the function correctly retrieves the 'next_url' from the pagination dictionary when pagination_format is 'next_url', following the specified business logic.

Scenario 2: Test when pagination_format is 'dict'
Details:
  TestName: test_build_pagination_info_dict
  Description: This test is intended to verify that the function returns the entire pagination dictionary when pagination_format is set as 'dict'.
Execution:
  Arrange: Initialize an instance of the class with pagination_format set to 'dict'. Prepare a content_obj with a 'pagination' dictionary.
  Act: Call the _build_pagination_info method with the prepared content_obj.
  Assert: Check that the returned value matches the entire 'pagination' dictionary from the content_obj.
Validation:
  This test validates that the function correctly returns the entire pagination dictionary when the pagination_format is 'dict', as per the defined business logic.

Scenario 3: Test when pagination_format is neither 'dict' nor 'next_url'
Details:
  TestName: test_build_pagination_info_invalid
  Description: This test is intended to verify that the function raises an Exception when pagination_format is neither 'dict' nor 'next_url'.
Execution:
  Arrange: Initialize an instance of the class with pagination_format set to a value other than 'dict' or 'next_url'.
  Act: Call the _build_pagination_info method with any content_obj.
  Assert: Check that an Exception is raised.
Validation:
  This test confirms that the function correctly raises an Exception when pagination_format is not a valid value, ensuring the integrity of the pagination information. 

Scenario 4: Test when 'pagination' is not in content_obj
Details:
  TestName: test_build_pagination_info_no_pagination
  Description: This test is intended to verify that the function returns None when 'pagination' is not in the content_obj.
Execution:
  Arrange: Initialize an instance of the class with any pagination_format. Prepare a content_obj without a 'pagination' dictionary.
  Act: Call the _build_pagination_info method with the prepared content_obj.
  Assert: Check that the returned value is None.
Validation:
  This test verifies that the function correctly handles a scenario where 'pagination' is not in the content_obj, returning None as expected.
"""

# ********RoostGPT********
import pytest
import urllib
from oauth2 import OAuth2Request
import re
from json_import import simplejson
import hmac
from hashlib import sha256
import six
from six.moves.urllib.parse import quote
import sys
from bind import _build_pagination_info


class Test_InstagramApiMethodBuildPaginationInfo:

    def test_build_pagination_info_next_url(self):
        class InstagramAPIMethod:
            def __init__(self):
                self.pagination_format = 'next_url'

            _build_pagination_info = _build_pagination_info

        api_method = InstagramAPIMethod()
        content_obj = {'pagination': {'next_url': 'https://example.com/page2'}}

        result = api_method._build_pagination_info(content_obj)

        assert result == 'https://example.com/page2'

    def test_build_pagination_info_dict(self):
        class InstagramAPIMethod:
            def __init__(self):
                self.pagination_format = 'dict'

            _build_pagination_info = _build_pagination_info

        api_method = InstagramAPIMethod()
        content_obj = {'pagination': {'next_url': 'https://example.com/page2', 'key': 'value'}}

        result = api_method._build_pagination_info(content_obj)

        assert result == {'next_url': 'https://example.com/page2', 'key': 'value'}

    def test_build_pagination_info_invalid(self):
        class InstagramAPIMethod:
            def __init__(self):
                self.pagination_format = 'invalid'

            _build_pagination_info = _build_pagination_info

        api_method = InstagramAPIMethod()
        content_obj = {'pagination': {'next_url': 'https://example.com/page2'}}

        with pytest.raises(Exception) as excinfo:
            api_method._build_pagination_info(content_obj)

        assert 'Invalid value for pagination_format' in str(excinfo.value)

    def test_build_pagination_info_no_pagination(self):
        class InstagramAPIMethod:
            def __init__(self):
                self.pagination_format = 'next_url'

            _build_pagination_info = _build_pagination_info

        api_method = InstagramAPIMethod()
        content_obj = {}

        result = api_method._build_pagination_info(content_obj)

        assert result is None
