# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_build_pagination_info_7cb90732ec
ROOST_METHOD_SIG_HASH=_build_pagination_info_fb4505ce87


Scenario 1: Test for Next Url Pagination
Details:
  TestName: test_next_url_pagination
  Description: This test verifies that the function returns the appropriate 'next_url' from the content_object when the pagination format is 'next_url'.
Execution:
  Arrange: Initialize a content_obj variable with a 'pagination' key containing a 'next_url' key.
  Act: Invoke _build_pagination_info(content_obj).
  Assert: Validate if the returned value is the same as the 'next_url' in the input.
Validation:
  Rationale: This validates that the function correctly extracts the 'next_url' when the pagination format is 'next_url', respecting the business logic encapsulated by the function.

Scenario 2: Test for Dict Pagination
Details:
  TestName: test_dict_pagination
  Description: This test ensures that if 'dict' is the pagination format, the function should return the entire pagination dictionary.
Execution:
  Arrange: Prepare a content_obj variable with a 'pagination' key.
  Act: Call the _build_pagination_info function with the prepared content_obj.
  Assert: Check whether the output matches the entire 'pagination' dictionary.
Validation: 
  Rationale: It is essential to ensure that the appropriate 'pagination' dictionary is returned when the pagination_format is 'dict'. This ensures the integrity of the product's business logic.

Scenario 3: Invalid Pagination Format 
Details:
  TestName: test_invalid_pagination_format
  Description: This test checks whether the function correctly raises an exception when an unsupported pagination format is provided.
Execution:
  Arrange: Set up a content_obj variable along with an unsupported value for pagination_format.
  Act: Invoke _build_pagination_info(content_obj).
  Assert: Confirm that an exception is thrown with the expected error message.
Validation:
  Rationale: The function should handle edge-cases, such as unsupported pagination formats, in a predictable manner, hence maintaining the stability and reliability of the system. 

Scenario 4: Pagination Key Absent 
Details:
  TestName: test_no_pagination_key
  Description: This test verifies if the function behaves appropriately when the 'pagination' key is missing in the content_obj.
Execution:
  Arrange: Set up a content_obj variable without a 'pagination' key.
  Act: Call the _build_pagination_info function with the prepared content_object.
  Assert: Verify if the returned value is None.
Validation:
  Rationale: This ensures that the function accommodates instances where the content object does not contain a 'pagination' key, thus improving its robustness and reliability.
"""

# ********RoostGPT********
import pytest
from bind import _build_pagination_info


class Test_BindBuildPaginationInfo:

    def test_next_url_pagination(self):
        # Arrange 
        content_obj = {'pagination': {'next_url': 'http://test-url-next-page.com'}}
        pagination_format = 'next_url'
        
        # Act
        result = _build_pagination_info(content_obj, pagination_format)
        
        # Assert
        assert result == 'http://test-url-next-page.com', "Test Failed: the returned URL does not match the expected next_url"
        
    def test_dict_pagination(self):
        # Arrange
        content_obj = {'pagination': {'page': 1, 'results': [{'user': 'user1'}, {'user': 'user2'}]}}
        pagination_format = 'dict'
        
        # Act
        result = _build_pagination_info(content_obj, pagination_format)
        
        # Assert
        assert result == {'page': 1, 'results': [{'user': 'user1'}, {'user': 'user2'}]}, "Test Failed: the returned dict does not match the expected pagination dictionary"
        
    def test_invalid_pagination_format(self):
        # Arrange
        content_obj = {'pagination': {'page': 1, 'results': [{'user': 'user1'}, {'user': 'user2'}]}}
        pagination_format = 'invalid_format'
        
        # Act and Assert
        with pytest.raises(Exception) as exc:
            result = _build_pagination_info(content_obj, pagination_format)
        assert str(exc.value) == 'Invalid value for pagination_format: %s' % pagination_format, "Test Failed: The invalid pagination format did not raise the expected exception"
        

    def test_no_pagination_key(self):
        # Arrange
        content_obj = {}
        pagination_format = None
        
        # Act
        result = _build_pagination_info(content_obj, pagination_format)
        
        # Assert
        assert result is None, "Test Failed: the function did not return None when pagination key is missing in the content_obj"
