# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type  and AI Model 

ROOST_METHOD_HASH=__init___54b35e0374
ROOST_METHOD_SIG_HASH=__init___fbf6974235


Scenario 1: Validate initial description assignment in constructor
Details:
  TestName: test_description_assignment_in_constructor
  Description: The test is intended to verify that the constructor assigns description correctly to the class object and no issues occur during assignment.
Execution:
  Arrange: Initialize a new class object with a description parameter.
  Act: Access the description property of the class object.
  Assert: Validate if the assigned description matches the supplied description value.
Validation:
  The result is connected to the function's specification, and importance is based on the fact that correct description assignment is key to further operations in the class.

Scenario 2: Validate Non-Empty description assignment
Details:
  TestName: test_non_empty_description_assignment
  Description: This test is intended to verify that the constructor does not accept an empty description. 
Execution:
  Arrange: Initialize a new object with an empty string as the description.
  Act: N/A
  Assert: The method should raise a value error when the description is empty.
Validation:
  The test is essential in that a class object should not be initialized with an empty description, according to predesigned business logic.

Scenario 3: Test Length of Description
Details:
  TestName: test_length_of_description
  Description: This test is intended to verify that the constructor does not accept a description that exceeds a predetermined length.
Execution:
  Arrange: Initialize a new object with a description string exceeding the allowed length.
  Act: N/A
  Assert: The method should raise a ValueError when the description is too long.
Validation:
  Descriptions that exceed a certain length might cause issues further down the line, the function should therefore have a limit on the length of the description.

Scenario 4: Validate Type of Description
Details:
  TestName: test_description_type
  Description: This test is intended to confirm the type of the description variable - it should only accept string types.
Execution:
  Arrange: Initialize a new object with a non-string type description.
  Act: N/A
  Assert: The method should raise a TypeError when non-string type descriptions are provided.
Validation:
  Ensuring the correct type for the description variable is important as it may be used in operations that only accept string type.
"""

# ********RoostGPT********
import pytest
from instagram.oauth2 import OAuth2AuthExchangeError

class Test_OAuth2AuthExchangeErrorInit:

    def test_description_assignment_in_constructor(self):
        description_val = "test description"
        obj = OAuth2AuthExchangeError(description_val)
        assert obj.description == description_val, "Failure: Discrepancy between assignment and initialization of description."

    def test_non_empty_description_assignment(self):
        description_val = ""
        with pytest.raises(ValueError, match="Description cannot be empty"):
            OAuth2AuthExchangeError(description_val)

    def test_length_of_description(self):
        description_val = "A" * 256
        with pytest.raises(ValueError, match="Description is too long"):
            OAuth2AuthExchangeError(description_val)

    def test_description_type(self):
        description_val = 12345
        with pytest.raises(TypeError, match="Description should be a string"):
            OAuth2AuthExchangeError(description_val)
