# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_build_path_ff2ab6973b
ROOST_METHOD_SIG_HASH=_build_path_6046ad27bf


```
Scenario 1: Evaluating parameter substation
Details:
  TestName: test_param_substitution
  Description: This test is intended to verify that the function can correctly substitute variables in the path with the corresponding values from self.parameters.
Execution:
  Arrange: Initialize an instance of the class that contains this method, ensuring that the path contains variables and the self.parameters dict contains corresponding keys.
  Act: Invoke the _build_path method for the instance.
  Assert: The path should be modified such that all variables are replaced with corresponding quoted values from self.parameters.
Validation: 
  The functionality of replacing path variables with parameters is very crucial in defining correct routes in API requests. Thus, proper functioning of this aspect helps in maintaining integrity of API calls.

Scenario 2: Evaluating the absence of required parameters
Details: 
  Test_name: test_absence_of_parameters
  Description: This test is designed to ascertain that the system raises an Exception when a variable found in the path isn't present within the parameters.
Execution:
  Arrange: Create an instance of the object with variables in the path and some missing keys in the self.parameters.
  Act: Call the function _build_path.
  Assert: An exception should be raised indicating the missing parameter.
Validation:
  The error raise is integral to alert the programmer about missing parameters in the path. This is essential for the API request to work as expected.

Scenario 3: Evaluating function behavior with format suffix
Details:
  TestName: test_path_with_format_suffix
  Description: This test is expected to verify that the function correctly appends a format suffix when the exclude_format variable is False or not set.
Execution:
  Arrange: Initialize an instance of the class with valid path variables and parameters and set self.api.format and leave self.exclude_format as False or unset.
  Act: Run the _build_path function.
  Assert: Check that the path is appended with format suffix.
Validation:
  Ensuring the function correctly handles path formatting by appending the right format suffix is crucial as incorrect API paths can lead to errors.

Scenario 4: Evaluating behavior when exclude_format is set to True
Details:
  TestName: test_exclude_format
  Description: This is to verify that the function can exclude format appending when the variable exclude_format is set to True.
Execution: 
  Arrange: Initialize an instance with self.exclude_format set to True.
  Act: Run the _build_path function.
  Assert: The path should not be appended with any format suffix.
Validation: 
  It is important for this function to be able to exclude the format suffix when required, especially when dealing with APIs that do not support it or have different rules.
"""

# ********RoostGPT********
import re
from urllib.parse import quote
from json_import import simplejson
import hmac
from hashlib import sha256
import six
from six.moves.urllib.parse import quote
import sys

re_path_template = re.compile('(\{[a-zA-Z_][a-zA-Z_0-9]*\})')

class OAuth2Request:
    def __init__(self, path, parameters, api_format=None, exclude_format=False):
        self.path = path
        self.api = lambda: None
        self.api.format = api_format
        self.parameters = parameters
        self.exclude_format = exclude_format

    def _build_path(self):
        for variable in re_path_template.findall(self.path):
            name = variable.strip('{}')

            if name not in self.parameters:
                raise Exception('No parameter value found for path variable: %s' % name)

            value = quote(self.parameters[name])
            del self.parameters[name]

            self.path = self.path.replace(variable, value)

        if self.api.format and not self.exclude_format:
            self.path = self.path + '.%s' % self.api.format
