# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=deregister_callback_d397189279
ROOST_METHOD_SIG_HASH=deregister_callback_9225e150e0


Scenario 1: Deregistering callback for given object type when callback exists
Details:
  TestName: test_deregister_callback_when_callback_exists
  Description: This test is intended to verify if the call to `deregister_callback` removes the callback for the given object type when such callback exists.
Execution:
  Arrange: Initialize an object of the class. Register a callback for a certain object type.
  Act: Call the `deregister_callback` function with the existing object type and the registered callback.
  Assert: Check if the callback of the given object type are removed from `self.callbacks`.
Validation:
  The success of this test guarantees that the `deregister_callback` method can successfully remove an existing callback for a certain object type, which is the core functionality of this method.

Scenario 2: Deregistering callback for given object type when callback does not exist
Details:
  TestName: test_deregister_callback_when_callback_does_not_exist
  Description: This test is intended to verify if the `deregister_callback` handles an attempt to deregister a non-existing callback appropriately.
Execution:
  Arrange: Initialize an object of the class.
  Act: Call the `deregister_callback` function with an object type and a callback, which was not previously registered.
  Assert: The call to `deregister_callback` should raise a ValueError indicating that the callback does not exist in the list of callbacks for the given object type.
Validation:
  The importance of this test lies in verifying the integrity of the `deregister_callback` method when faced with an erroneous operation – trying to remove a non-existing callback. Handling this error adequately is crucial to the overall stability of the software.

Scenario 3: Deregistering callback when object type does not exist
Details:
  TestName: test_deregister_callback_when_object_type_does_not_exist
  Description: This test is intended to verify if the `deregister_callback` handles an attempt to deregister a callback from a non-existing object type appropriately.
Execution:
  Arrange: Initialize an object of the class.
  Act: Call the `deregister_callback` with a non-existing object type and a random callback.
  Assert: Since there are no callbacks for the non-existing object type, the call to `deregister_callback` should not affect the `self.callbacks` dictionary.
Validation:
  This test is important to verify that the `deregister_callback` method handles scenarios where the object type does not exist in a graceful manner without affecting the stability of the overall software and its state.
"""

# ********RoostGPT********
import pytest
import hmac, hashlib
from json_import import simplejson
from subscriptions import SubscriptionsReactor

class Test_SubscriptionsReactorDeregisterCallback:

    @pytest.mark.regression
    def test_deregister_callback_when_callback_exists(self):
        subscriptionsReactor = SubscriptionsReactor()
        object_type = "Object_1"
        callback = lambda x : x
        subscriptionsReactor.callbacks = {object_type: [callback]}
        subscriptionsReactor.deregister_callback(object_type, callback)
        assert subscriptionsReactor.callbacks == {}

    @pytest.mark.regression
    def test_deregister_callback_when_callback_does_not_exist(self):
        subscriptionsReactor = SubscriptionsReactor()
        object_type = "Object_1"
        callback = lambda x : x
        error_message = "list.remove(x): x not in list"
        with pytest.raises(ValueError, match = error_message):
            subscriptionsReactor.deregister_callback(object_type, callback)

    @pytest.mark.regression
    def test_deregister_callback_when_object_type_does_not_exist(self):
        subscriptionsReactor = SubscriptionsReactor()
        object_type = "Object_1"
        non_existing_object_type = "Object_2"
        callback = lambda x : x
        subscriptionsReactor.callbacks = {object_type: [callback]}
        subscriptionsReactor.deregister_callback(non_existing_object_type, callback)
        assert subscriptionsReactor.callbacks == {object_type: [callback]}
