# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_do_api_request_ef7e819545
ROOST_METHOD_SIG_HASH=_do_api_request_48da8e3e50


```
Scenario 1: Test successful GET request
Details:
  TestName: test_successful_get_request
  Description: This test is intended to verify that the function _do_api_request properly handles a successful GET request.
Execution:
  Arrange: Initialize an Instagram API object with valid credentials and a valid endpoint.
  Act: Call the function _do_api_request with the initialized Instagram API object and the "GET" method.
  Assert: Check that the function returns a response with a status code of 200 and the expected content.
Validation:
  This test is important because it ensures that the function can successfully handle a basic GET request, which is a fundamental operation of the API.

Scenario 2: Test successful POST request
Details:
  TestName: test_successful_post_request
  Description: This test is intended to verify that the function _do_api_request properly handles a successful POST request.
Execution:
  Arrange: Initialize an Instagram API object with valid credentials and a valid endpoint. Prepare a body for the POST request.
  Act: Call the function _do_api_request with the initialized Instagram API object, the "POST" method, and the prepared body.
  Assert: Check that the function returns a response with a status code of 200 and the expected content.
Validation:
  This test is important because it ensures that the function can successfully handle a POST request, which is necessary for creating or updating data on the server.

Scenario 3: Test handling of rate limiting
Details:
  TestName: test_rate_limiting
  Description: This test is intended to verify that the function _do_api_request properly handles a response indicating rate limiting.
Execution:
  Arrange: Initialize an Instagram API object with valid credentials and a valid endpoint. Prepare the environment to return a response with a status code of 503 or 429 when the function is called.
  Act: Call the function _do_api_request with the initialized Instagram API object.
  Assert: Check that the function raises an InstagramAPIError with a message indicating rate limiting.
Validation:
  This test is important because it ensures that the function properly handles rate limiting, which is a common occurrence when dealing with APIs and needs to be handled gracefully.

Scenario 4: Test handling of invalid JSON response
Details:
  TestName: test_invalid_json_response
  Description: This test is intended to verify that the function _do_api_request properly handles a response with invalid JSON.
Execution:
  Arrange: Initialize an Instagram API object with valid credentials and a valid endpoint. Prepare the environment to return a response with invalid JSON when the function is called.
  Act: Call the function _do_api_request with the initialized Instagram API object.
  Assert: Check that the function raises an InstagramClientError with a message indicating that the response could not be parsed as JSON.
Validation:
  This test is important because it ensures that the function can gracefully handle a response with invalid JSON, which could occur due to a server error or other unexpected circumstances.

Scenario 5: Test handling of API error response
Details:
  TestName: test_api_error_response
  Description: This test is intended to verify that the function _do_api_request properly handles a response indicating an API error.
Execution:
  Arrange: Initialize an Instagram API object with valid credentials and a valid endpoint. Prepare the environment to return a response with a status code other than 200 when the function is called.
  Act: Call the function _do_api_request with the initialized Instagram API object.
  Assert: Check that the function raises an InstagramAPIError with the status code and error message from the response.
Validation:
  This test is important because it ensures that the function can properly handle an API error, which could occur for a variety of reasons and needs to be passed on to the caller for appropriate handling.
```
"""

# ********RoostGPT********
import pytest
from unittest.mock import patch
from bind import InstagramAPIError, InstagramClientError

# Import the function to be tested
from bind import _do_api_request

@pytest.mark.parametrize("response_status, expected_exception, expected_message", [
    ('503', InstagramAPIError, "Your client is making too many request per second"),
    ('429', InstagramAPIError, "Your client is making too many request per second"),
    ('400', InstagramAPIError, "Some API Error"),
    ('200', None, None),
])
def test_do_api_request(response_status, expected_exception, expected_message):
    mock_response = {"status": response_status}
    mock_content = '{"meta":{"code":200,"error_type":"Some API Error","error_message":"Some API Error"}}'
    with patch('bind.OAuth2Request') as mock_request:
        mock_request().make_request.return_value = (mock_response, mock_content)
        if expected_exception:
            with pytest.raises(expected_exception) as e_info:
                _do_api_request('url', 'GET')
            assert str(e_info.value) == expected_message
        else:
            _do_api_request('url', 'GET')
            assert mock_request().make_request.called

def test_do_api_request_invalid_json():
    mock_response = {"status": '200'}
    mock_content = 'This is not valid JSON'
    with patch('bind.OAuth2Request') as mock_request:
        mock_request().make_request.return_value = (mock_response, mock_content)
        with pytest.raises(InstagramClientError) as e_info:
            _do_api_request('url', 'GET')
        assert str(e_info.value) == 'Unable to parse response, not valid JSON.'

def test_do_api_request_post():
    mock_response = {"status": '200'}
    mock_content = '{"meta":{"code":200}}'
    with patch('bind.OAuth2Request') as mock_request:
        mock_request().make_request.return_value = (mock_response, mock_content)
        _do_api_request('url', 'POST', body='body')
        mock_request().make_request.assert_called_with('url', method='POST', body='body', headers=None)
